push: update app if app name already exists
Currently, if a developer tries to push new source code to an app that
has already been deployed, they will get the following error:

```
Error: services.serving.knative.dev "app-name" already exists
services.serving.knative.dev "app-name" already exists
```

This CL makes Push look to see if that app has already been pushed, and
instead uses Update in lieu of Create. It will set the ResourceVersion
to the previous version.

This also moves the pkg/kf tests to the `kf_test` package.

Change-Id: I2459d381f2701c2ae73a1827abb7e21f928ac303